version: '3.8'
services:
  web:
    build: ./web
    env_file: .env
    ports: ["3000:3000"]
  api:
    build: ./api
    env_file: .env
    ports: ["8000:8000"]
  db:
    image: postgres:15
    restart: always
    env_file: .env
    volumes:
      - db_data:/var/lib/postgresql/data
volumes:
  db_data:
