on: [pull_request]
jobs:
  test-api:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v4
        with: python-version: 3.10
      - run: cd api && pip install -r requirements.txt
      - run: cd api && pytest  # write some basic tests
