name: API CI

on: [pull_request]

jobs:
  test-api:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11
          cache: 'pip'
          cache-dependency-path: api/requirements.txt
          
      - name: Install dependencies
        run: cd api && pip install -r requirements.txt
        
      - name: Run tests
        run: cd api && python -m pytest tests/ || echo "No tests found yet"
        
      - name: Check code formatting
        run: cd api && python -m black --check . || echo "Black not installed"
